-- Migration 002: Outcome billing events table
-- MIN-347 — Stripe billing bridge (Component 3 of MIN-240)
--
-- Safe to run on fresh DB or existing DB (all statements use IF NOT EXISTS).
-- Adapts PostgreSQL plan schema to SQLite-compatible types:
--   - UUID → TEXT (generated in application layer via crypto.randomUUID())
--   - TIMESTAMPTZ → TEXT (ISO-8601 strings) or INTEGER (Unix ms) as appropriate
--   - gen_random_uuid() → handled by application code
--
-- To roll back:
--   DROP INDEX IF EXISTS idx_billing_events_next_retry;
--   DROP INDEX IF EXISTS idx_billing_events_idempotency;
--   DROP INDEX IF EXISTS idx_billing_events_customer;
--   DROP INDEX IF EXISTS idx_billing_events_status;
--   DROP TABLE IF EXISTS outcome_billing_events;

CREATE TABLE IF NOT EXISTS outcome_billing_events (
  id                          TEXT PRIMARY KEY,   -- UUID generated by app
  customer_id                 TEXT NOT NULL,
  task_id                     TEXT NOT NULL,
  agent_id                    TEXT NOT NULL,
  outcome_definition_id       TEXT NOT NULL,
  outcome_definition_version_id TEXT NOT NULL,
  amount                      INTEGER NOT NULL,   -- cents
  currency                    TEXT NOT NULL DEFAULT 'usd',
  outcome                     TEXT NOT NULL CHECK(outcome IN ('success', 'partial')),
  detected_at                 TEXT NOT NULL,      -- ISO-8601
  stripe_meter_name           TEXT,
  stripe_event_id             TEXT,
  idempotency_key             TEXT NOT NULL UNIQUE, -- task_id + ':' + outcome_definition_id
  status                      TEXT NOT NULL DEFAULT 'pending'
                                CHECK(status IN ('pending', 'emitted', 'failed', 'retrying', 'buffered')),
  retry_count                 INTEGER NOT NULL DEFAULT 0,
  last_error                  TEXT,
  next_retry_at               TEXT,               -- ISO-8601; NULL until first failure
  emitted_at                  TEXT,               -- ISO-8601; NULL until emitted
  created_at                  TEXT NOT NULL,      -- ISO-8601
  updated_at                  TEXT NOT NULL       -- ISO-8601
);

-- Partial index: only non-emitted rows need fast status lookup (retry processor)
CREATE INDEX IF NOT EXISTS idx_billing_events_status
  ON outcome_billing_events(status)
  WHERE status != 'emitted';

CREATE INDEX IF NOT EXISTS idx_billing_events_customer
  ON outcome_billing_events(customer_id);

CREATE INDEX IF NOT EXISTS idx_billing_events_idempotency
  ON outcome_billing_events(idempotency_key);

-- Allows the retry processor to efficiently find due retries
CREATE INDEX IF NOT EXISTS idx_billing_events_next_retry
  ON outcome_billing_events(next_retry_at)
  WHERE status = 'retrying';
