// AUTO-GENERATED — do not edit. Run: pnpm generate:tools

export const GENERATED_TOOL_GROUPS: Record<string, string[]> = {
  "group:automation": ["cron", "gateway"],
  "group:gog": ["gog_auth_revoke", "gog_auth_start", "gog_auth_status", "gog_exec"],
  "group:memory": ["knowledge_graph"],
  "group:messaging": ["message"],
  "group:minion": [
    "agents_list",
    "architect_pipeline",
    "browse_web",
    "browser",
    "canvas",
    "cron",
    "gateway",
    "gog_auth_revoke",
    "gog_auth_start",
    "gog_auth_status",
    "gog_exec",
    "image",
    "knowledge_graph",
    "message",
    "nodes",
    "parse_screen",
    "session_status",
    "sessions_history",
    "sessions_list",
    "sessions_send",
    "sessions_spawn",
    "subagents",
    "summarize",
    "tts",
    "venture_studio",
    "web_fetch",
    "web_search",
  ],
  "group:nodes": ["nodes"],
  "group:sessions": [
    "session_status",
    "sessions_history",
    "sessions_list",
    "sessions_send",
    "sessions_spawn",
    "subagents",
  ],
  "group:ui": ["browser", "canvas", "parse_screen"],
  "group:web": ["browse_web", "web_fetch", "web_search"],
};
