import { html, nothing, type TemplateResult } from "lit";

const SESSION_KEY = "minion-ai-disclosure-collapsed";
const DEFAULT_DISCLOSURE = "Generated by AI";

function isCollapsed(): boolean {
  try {
    return sessionStorage.getItem(SESSION_KEY) === "1";
  } catch {
    return false;
  }
}

function setCollapsed(collapsed: boolean): void {
  try {
    if (collapsed) {
      sessionStorage.setItem(SESSION_KEY, "1");
    } else {
      sessionStorage.removeItem(SESSION_KEY);
    }
  } catch {
    // sessionStorage unavailable — collapse state stays in-memory only
  }
}

/**
 * Syncs all disclosure badges on the page to the same collapsed state.
 */
function syncAllBadges(collapsed: boolean): void {
  const badges = document.querySelectorAll<HTMLElement>(".ai-disclosure");
  for (const badge of badges) {
    const text = badge.querySelector<HTMLElement>(".ai-disclosure__text");
    const btn = badge.querySelector<HTMLButtonElement>(".ai-disclosure__toggle");
    if (text) {
      text.hidden = collapsed;
    }
    if (btn) {
      btn.setAttribute("aria-expanded", String(!collapsed));
      btn.title = collapsed ? "Show AI disclosure" : "Collapse AI disclosure";
      btn.setAttribute(
        "aria-label",
        collapsed ? "Show AI disclosure" : "Collapse AI disclosure",
      );
    }
  }
}

/**
 * Renders an AI disclosure badge for EU AI Act Article 50 compliance.
 *
 * - Displays `disclosure` text (defaults to "Generated by AI")
 * - Collapse/expand toggle with session-only persistence
 * - Screen reader accessible with role="status" and ARIA attributes
 * - Keyboard navigable
 */
export function renderAIDisclosureBadge(disclosure?: string): TemplateResult {
  const text = disclosure?.trim() || DEFAULT_DISCLOSURE;
  const collapsed = isCollapsed();

  return html`
    <span class="ai-disclosure" role="status" aria-label="${text}">
      <span
        class="ai-disclosure__text"
        ?hidden=${collapsed}
      >${text}</span>
      <button
        class="ai-disclosure__toggle"
        type="button"
        title=${collapsed ? "Show AI disclosure" : "Collapse AI disclosure"}
        aria-label=${collapsed ? "Show AI disclosure" : "Collapse AI disclosure"}
        aria-expanded=${String(!collapsed)}
        @click=${(e: Event) => {
          e.stopPropagation();
          const nowCollapsed = !isCollapsed();
          setCollapsed(nowCollapsed);
          syncAllBadges(nowCollapsed);
        }}
      >
        ${collapsed ? "●" : "○"}
      </button>
    </span>
  `;
}

/**
 * Renders the disclosure badge only for assistant roles.
 * Returns `nothing` for user or other roles.
 */
export function renderDisclosureForRole(
  role: string,
  disclosure?: string,
): TemplateResult | typeof nothing {
  if (role !== "assistant") {
    return nothing;
  }
  return renderAIDisclosureBadge(disclosure);
}
